site_name: xminstrel's blog
nav:
  - Home: index.md
  - 关于赤奈: about_me.md
  - 控制相关:
    - 控制论: 控制相关/控制论.md
    - 自动控制理论: 控制相关/自动控制理论.md
    - Esp32 入门: 控制相关/Esp32.md
    - stm32 入门: 控制相关/stm32.md
markdown_extensions:
  - wikilinks # 开启 Wiki 链接支持

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
theme:
  name: material
  custom_dir: overrides
  language: zh
  favicon: assets/images/favicon.png  # 这里写从 docs 目录开始的相对路径
  palette: 
    # 切换日间模式 (点击右上角按钮)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo  # 主色调 (顶部栏)
      accent: indigo   # 强调色 (链接、按钮)
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # 切换夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate    # 这里是重点！slate 是自带的深色高级配色
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs        # 开启顶部导航栏 (像App一样)
    - navigation.sections    # 侧边栏分组
    - toc.integrate          # 将目录集成到左侧
    - navigation.top         # 返回顶部按钮
    - search.suggest         # 搜索建议
    - search.highlight       # 搜索高亮

# 换个字体 (自动从 Google Fonts 拉取)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xminstrel
