site_name: xminstrel's blog
site_author: èµ¤å¥ˆè‰¯ç³
site_url: 'https://xminstrel.github.io/'
# ç«™ç‚¹åŸºæœ¬ä¿¡æ¯
nav:
  - "ğŸ† é¦–é¡µ": index.md
  - ğŸ˜˜ å…³äºèµ¤å¥ˆ: about_me.md
  - ğŸ’ AI ç›¸å…³: 
    - AIå·¥å…·: ai/tools.md
  - ğŸª¡ æ§åˆ¶ç›¸å…³:
    - æ§åˆ¶è®º: control/æ§åˆ¶è®º.md
    - è‡ªåŠ¨æ§åˆ¶ç†è®º: control/è‡ªåŠ¨æ§åˆ¶ç†è®º.md
    - Esp32 å…¥é—¨: control/Esp32.md
    - stm32 å…¥é—¨: control/stm32.md
  - ğŸ–¼ï¸ å…¶ä»–ç¬”è®°: 
    -  emm: others/index.md
# è‡ªå®šä¹‰æ ·å¼å’Œè„šæœ¬
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
#ä¸»é¢˜é…ç½®
theme:
  name: material
  custom_dir: overrides
  language: zh
  favicon: assets/images/favicon.png  # è¿™é‡Œå†™ä» docs ç›®å½•å¼€å§‹çš„ç›¸å¯¹è·¯å¾„
  #icon:
    #repo: fontawesome/brands/github
  font:
    text: LXGW WenKai Screen GB Screen # Share Tech
    code: JetBrains Mono
  palette: 
    # åˆ‡æ¢æ—¥é—´æ¨¡å¼ (ç‚¹å‡»å³ä¸Šè§’æŒ‰é’®)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo  # ä¸»è‰²è°ƒ (é¡¶éƒ¨æ )
      accent: indigo   # å¼ºè°ƒè‰² (é“¾æ¥ã€æŒ‰é’®)
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # åˆ‡æ¢å¤œé—´æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate  
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs        # å¼€å¯é¡¶éƒ¨å¯¼èˆªæ  (åƒAppä¸€æ ·)
    - navigation.sections    # ä¾§è¾¹æ åˆ†ç»„
    - toc.integrate          # å°†ç›®å½•é›†æˆåˆ°å·¦ä¾§
    - navigation.top         # è¿”å›é¡¶éƒ¨æŒ‰é’®
    - search.suggest         # æœç´¢å»ºè®®
    - search.highlight       # æœç´¢é«˜äº®
#mdæ‰©å±•
markdown_extensions:
  - wikilinks
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# ç¤¾äº¤åª’ä½“é“¾æ¥é…ç½®
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xminstrel
      name: GitHub

# ä»“åº“é“¾æ¥é…ç½®
repo_url: https://github.com/xminstrel/xminstrel.github.io
repo_name: xminstrel
edit_uri: edit/main/docs/